=== filip13111998/XML-Vaccination/Sluzbenik servis/sluzbenik/src/main/resources/schemas/interesovanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:util="http://ftn.uns.ac.rs/util"
           targetNamespace = "http://ftn.uns.ac.rs/interesovanje"
           xmlns:in="http://ftn.uns.ac.rs/interesovanje"
           elementFormDefault="qualified">
    
    
    
    
    <xs:import namespace="http://ftn.uns.ac.rs/util" schemaLocation="util.xsd"/>
    
    <xs:element name = "interesovanje">    
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "drzavljanin" type = "util:TDrzavljanin" minOccurs = "1" maxOccurs = "1"/>
                
                <xs:element name = "jmbg" type = "util:TJmbg" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "ime" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "prezime" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "e-mail" type = "util:TMail" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "mobilni" type = "util:TMobilni" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "fiksni" type = "util:TFiksni" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "lokacija" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "tipVakcina" type = "util:TTipVakcina" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "davalac" type = "util:TDavalacKrvi" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "datum" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>

            </xs:sequence>
            <xs:attribute name="id_interesovanje" type="xs:string"/>
            
        </xs:complexType>
    </xs:element>
</xs:schema>

=== filip13111998/XML-Vaccination/XML-Shema/interesovanje11.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:interesovanje xmlns:util="http://ftn.uns.ac.rs/util"
 xmlns:in="http://ftn.uns.ac.rs/interesovanje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/interesovanje file:/C:/Users/vaske/Desktop/XML-Vaccination/XML-Vaccination/XML-Shema/interesovanje.xsd" id_interesovanje="RgFKThHbcHiDeJRC">
    <in:drzavljanin>
        <util:StraniDrzavljaninBezBoravka>false</util:StraniDrzavljaninBezBoravka>
    </in:drzavljanin>
    <in:jmbg>6017014534610</in:jmbg>
    <in:ime>Mihailo</in:ime>
    <in:prezime>Bubnjevic</in:prezime>
    <in:e-mail>haha@gmail.com</in:e-mail>
    <in:mobilni>0616546951</in:mobilni>
    <in:fiksni>011909562</in:fiksni>
    <in:lokacija>Ljubovija</in:lokacija>
    <in:tipVakcina>
        <util:Pfizer-BioNTech>false</util:Pfizer-BioNTech>
    </in:tipVakcina>
    <in:davalac>
        <util:ne>true</util:ne>
    </in:davalac>
    <in:datum>1987</in:datum>
</in:interesovanje>

=== filip13111998/XML-Vaccination/XML-Shema/inter1.xml
<?xml version="1.0" encoding="UTF-8"?>
<in:interesovanje xmlns:util="http://ftn.uns.ac.rs/util"
 xmlns:in="http://ftn.uns.ac.rs/interesovanje"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/interesovanje file:/C:/Users/vaske/Desktop/XML-Vaccination/XML-Vaccination/XML-Shema/interesovanje.xsd" id_interesovanje="id_interesovanje0">
    <in:drzavljanin>
        <util:DrzavljaninSrbije>false</util:DrzavljaninSrbije>
    </in:drzavljanin>
    <in:jmbg>0000000000000</in:jmbg>
    <in:ime>ime0</in:ime>
    <in:prezime>prezime0</in:prezime>
    <in:e-mail> @ .a</in:e-mail>
    <in:mobilni>0600000000</in:mobilni>
    <in:fiksni>011000000</in:fiksni>
    <in:lokacija>lokacija0</in:lokacija>
    <in:tipVakcina>
        <util:Moderna>false</util:Moderna>
    </in:tipVakcina>
    <in:davalac>
        <util:da>false</util:da>
    </in:davalac>
    <in:datum>datum0</in:datum>
</in:interesovanje>
