=== filip13111998/XML-Vaccination/Sluzbenik servis/sluzbenik/src/main/resources/schemas/izvestaj_imunizacija.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:util="http://ftn.uns.ac.rs/util"
           targetNamespace = "http://ftn.uns.ac.rs/izvestaj"
           xmlns:iz="http://ftn.uns.ac.rs/izvestaj"
           elementFormDefault="qualified">
    
    <xs:import namespace="http://ftn.uns.ac.rs/util" schemaLocation="util.xsd"/>
    
    <xs:element name = "izvestaj">    
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "datumOd" type = "xs:date" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "datumDo" type = "xs:date" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "podnetiDokumenti" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "primljeno" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "izdato" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "dateVakcine" type = "xs:string" minOccurs = "1" maxOccurs = "1"/>
                <xs:element name = "doza" type = "util:TRednaDoza" maxOccurs = "unbounded"/>
                <!--<xs:element name = "drugaDoza" type = "xs:string" maxOccurs = "1"/>-->
               <!-- <xs:element name = "trecaDoza" type = "xs:string" maxOccurs = "1"/>-->
                <xs:element name = "fajzer" type = "xs:string" maxOccurs = "1"/>
                <xs:element name = "sputnjik" type = "xs:string"  maxOccurs = "1"/>
                <xs:element name = "moderna" type = "xs:string"  maxOccurs = "1"/>
                <xs:element name = "sinofarm" type = "xs:string"  maxOccurs = "1"/>
                <xs:element name = "astraZeneca" type = "xs:string" maxOccurs = "1"/>
                <xs:element name = "datumIzdavanja" type = "xs:date" minOccurs = "1" maxOccurs = "1"/>
                 
            </xs:sequence>
            <xs:attribute name="id_izvestaj" type="xs:string"/>
            
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== filip13111998/XML-Vaccination/Sluzbenik servis/sluzbenik-front/sluzbenik-frontend/src/assets/XMLfiles/izvestaj_o_imunizaciji.xml
<iz:izvestaj xmlns:util="http://ftn.uns.ac.rs/util"
             xmlns:iz="http://ftn.uns.ac.rs/izvestaj"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://ftn.uns.ac.rs/izvestaj file:/C:/Users/vaske/Desktop/XML-Vaccination/XML-Vaccination/XML-Shema/izvestaj_imunizacija.xsd">
  <iz:datumOd>2006-05-04</iz:datumOd>
  <iz:datumDo>2006-05-04</iz:datumDo>
  <iz:podnetiDokumenti>podnetiDokumenti0</iz:podnetiDokumenti>
  <iz:primljeno>primljeno0</iz:primljeno>
  <iz:izdato>izdato0</iz:izdato>
  <iz:dateVakcine>dateVakcine0</iz:dateVakcine>
  <iz:doza>doza0</iz:doza>
  <iz:doza>doza1</iz:doza>
  <iz:fajzer>410</iz:fajzer>
  <iz:sputnjik>13</iz:sputnjik>
  <iz:moderna>23</iz:moderna>
  <iz:sinofarm>0</iz:sinofarm>
  <iz:astraZeneca>42</iz:astraZeneca>
  <iz:datumIzdavanja>2006-05-04</iz:datumIzdavanja>
  <iz:potpis>potpis0</iz:potpis>
</iz:izvestaj>
